### ISSUE TITLE
Add VOLUME

### ISSUE THREAD

**Issue by eproxus** [lphoward/fake-s3#6]
It would be nice to have a `VOLUME` so the S3 data can be persisted outside of Docker.

**Comment by lphoward** [comment]
Sorry to have let this issue dangle, but it is not relevant to the orchestration.  Docker's capabilities for volumes can really be viewed as orthogonal.  E.g.,

    $ docker run --name my_s3 -v /fakes3_root -d lphoward/fake-s3

This will mount the fakeS3 root directory as a volume on the Docker host.  To see the host's location:

    $ docker inspect --format "{{range .Mounts}}{{.Source}}{{end}}" my_s3

The [Docker docs](https://docs.docker.com/engine/userguide/dockervolumes/) provide the details.

Since, as I understand it, the goal of the issue can already be achieved, I'll close it.  If I have misunderstood, please correct me.
